apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
 type: NodePort
 ports:
  - port: 8090
    targetPort: 8090
    protocol: TCP
 type: NodePort
 ports:
  - port: 8091
    targetPort: 8091
    protocol: TCP
 selector:
  app: webserver
